name: Rails CI

on:
  push:
    branches: [ master, main, develop ]
    paths:
      - 'backend-gifters/**'
  pull_request:
    branches: [ master, main, develop ]
    paths:
      - 'backend-gifters/**'

jobs:
  test:
    name: Tests & Linting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend-gifters

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: gifters_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/gifters_test
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      DEVISE_JWT_SECRET_KEY: ${{ secrets.DEVISE_JWT_SECRET_KEY || 'dummy_key_for_tests' }}
      BREVO_API_KEY: ${{ secrets.BREVO_API_KEY || 'dummy_api_key' }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'
          bundler-cache: true
          working-directory: ./backend-gifters

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Setup database
        run: |
          bundle exec rails db:create
          bundle exec rails db:schema:load

      - name: Run RuboCop
        run: |
          gem install rubocop
          rubocop --parallel

      - name: Run tests with SimpleCov
        run: |
          bundle exec rake spec COVERAGE=true

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage
          path: backend-gifters/coverage/

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend-gifters

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'
          bundler-cache: true
          working-directory: ./backend-gifters

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          gem install brakeman bundler-audit

      - name: Run Brakeman
        run: |
          brakeman -z -A

      - name: Run Bundle Audit
        run: |
          bundle-audit check --update

  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: [test, security]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./backend-gifters
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/gifters-backend:latest
            ghcr.io/${{ github.repository_owner }}/gifters-backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
