name: Rails CI

on:
  push:
    branches: [ master, main, develop ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master, main, develop ]
    paths-ignore:
      - '**.md'

jobs:
  test:
    name: Tests & Linting
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: gifters_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/gifters_test
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      DEVISE_JWT_SECRET_KEY: ${{ secrets.DEVISE_JWT_SECRET_KEY || 'dummy_key_for_tests' }}
      BREVO_API_KEY: ${{ secrets.BREVO_API_KEY || 'dummy_api_key' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'
          bundler-cache: false

      - name: Update RubyGems and Bundler
        run: |
          gem update --system
          gem install bundler -v 2.5.4

      - name: Install dependencies
        run: |
          bundle config set --local path 'vendor/bundle'
          bundle config set --local without 'development:test'
          bundle install --jobs 4 --retry 3

      - name: Show bundle environment
        run: |
          bundle env
          ruby -v
          bundler -v

      - name: Setup database
        run: |
          bundle exec rails db:create
          bundle exec rails db:schema:load

      - name: Run RuboCop
        run: |
          bundle exec rubocop --parallel || true

      - name: Run tests with SimpleCov
        run: |
          bundle exec rspec COVERAGE=true

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: coverage/

  security:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'
          bundler-cache: false

      - name: Update RubyGems and Bundler
        run: |
          gem update --system
          gem install bundler -v 2.5.4

      - name: Install dependencies
        run: |
          bundle config set --local path 'vendor/bundle'
          bundle config set --local without 'development:test'
          bundle install --jobs 4 --retry 3

      - name: Install security tools
        run: |
          gem install brakeman bundler-audit

      - name: Run Brakeman
        run: |
          brakeman -z -A || true

      - name: Run Bundle Audit
        run: |
          bundle-audit check --update || true
